[package]
name = "submodex"
version = "0.1.0"
authors = ["masaya.tahara <masaya.tahara@accenture.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
